//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVD中文游戏300 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameROM {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameROM() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DVD中文游戏300.GameROM", typeof(GameROM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _01_01_1942 {
            get {
                object obj = ResourceManager.GetObject("_01_01_1942", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _01_02_1943 {
            get {
                object obj = ResourceManager.GetObject("_01_02_1943", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _01_03_冒险岛 {
            get {
                object obj = ResourceManager.GetObject("_01_03_冒险岛", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _01_04_坦克 {
            get {
                object obj = ResourceManager.GetObject("_01_04_坦克", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _01_05_兵蜂 {
            get {
                object obj = ResourceManager.GetObject("_01_05_兵蜂", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _01_06_炸弹超人 {
            get {
                object obj = ResourceManager.GetObject("_01_06_炸弹超人", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _01_07_炸弹杰克 {
            get {
                object obj = ResourceManager.GetObject("_01_07_炸弹杰克", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _01_08_咖啡店 {
            get {
                object obj = ResourceManager.GetObject("_01_08_咖啡店", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _01_09_马戏团 {
            get {
                object obj = ResourceManager.GetObject("_01_09_马戏团", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _01_10_魂斗罗 {
            get {
                object obj = ResourceManager.GetObject("_01_10_魂斗罗", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _02_01_太空战士 {
            get {
                object obj = ResourceManager.GetObject("_02_01_太空战士", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _02_02_玛莉医生 {
            get {
                object obj = ResourceManager.GetObject("_02_02_玛莉医生", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _02_03_火龙 {
            get {
                object obj = ResourceManager.GetObject("_02_03_火龙", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _02_04_超级雷电 {
            get {
                object obj = ResourceManager.GetObject("_02_04_超级雷电", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _02_05_钻石方块 {
            get {
                object obj = ResourceManager.GetObject("_02_05_钻石方块", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _02_06_超级玛莉 {
            get {
                object obj = ResourceManager.GetObject("_02_06_超级玛莉", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _02_07_猪小弟 {
            get {
                object obj = ResourceManager.GetObject("_02_07_猪小弟", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _02_08_彩虹岛 {
            get {
                object obj = ResourceManager.GetObject("_02_08_彩虹岛", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _02_09_坦克2 {
            get {
                object obj = ResourceManager.GetObject("_02_09_坦克2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _02_10_俄罗斯方块 {
            get {
                object obj = ResourceManager.GetObject("_02_10_俄罗斯方块", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _03_01_橄榄球 {
            get {
                object obj = ResourceManager.GetObject("_03_01_橄榄球", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _03_02_辛巴达 {
            get {
                object obj = ResourceManager.GetObject("_03_02_辛巴达", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _03_03_百眼巨神 {
            get {
                object obj = ResourceManager.GetObject("_03_03_百眼巨神", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _03_04_打砖块 {
            get {
                object obj = ResourceManager.GetObject("_03_04_打砖块", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _03_05_爱心企鹅 {
            get {
                object obj = ResourceManager.GetObject("_03_05_爱心企鹅", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _03_06_气球大战 {
            get {
                object obj = ResourceManager.GetObject("_03_06_气球大战", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _03_07_汉堡时间 {
            get {
                object obj = ResourceManager.GetObject("_03_07_汉堡时间", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _03_08_B计划 {
            get {
                object obj = ResourceManager.GetObject("_03_08_B计划", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _03_09_迷魂车 {
            get {
                object obj = ResourceManager.GetObject("_03_09_迷魂车", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _03_10_五子棋 {
            get {
                object obj = ResourceManager.GetObject("_03_10_五子棋", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _04_01_拼图 {
            get {
                object obj = ResourceManager.GetObject("_04_01_拼图", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _04_02_战场 {
            get {
                object obj = ResourceManager.GetObject("_04_02_战场", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _04_03_挖掘者 {
            get {
                object obj = ResourceManager.GetObject("_04_03_挖掘者", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _04_04_金刚1代 {
            get {
                object obj = ResourceManager.GetObject("_04_04_金刚1代", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _04_05_金刚2代 {
            get {
                object obj = ResourceManager.GetObject("_04_05_金刚2代", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _04_06_金刚3代 {
            get {
                object obj = ResourceManager.GetObject("_04_06_金刚3代", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _04_07_篮球 {
            get {
                object obj = ResourceManager.GetObject("_04_07_篮球", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _04_08_龙战士 {
            get {
                object obj = ResourceManager.GetObject("_04_08_龙战士", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _04_09_电梯 {
            get {
                object obj = ResourceManager.GetObject("_04_09_电梯", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _04_10_火凤凰 {
            get {
                object obj = ResourceManager.GetObject("_04_10_火凤凰", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _05_01_救火队员 {
            get {
                object obj = ResourceManager.GetObject("_05_01_救火队员", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _05_02_机器人战争 {
            get {
                object obj = ResourceManager.GetObject("_05_02_机器人战争", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _05_03_前线 {
            get {
                object obj = ResourceManager.GetObject("_05_03_前线", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _05_04_小蜜蜂 {
            get {
                object obj = ResourceManager.GetObject("_05_04_小蜜蜂", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _05_05_高尔夫球 {
            get {
                object obj = ResourceManager.GetObject("_05_05_高尔夫球", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _05_06_七宝奇谋2 {
            get {
                object obj = ResourceManager.GetObject("_05_06_七宝奇谋2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _05_07_沙罗曼蛇 {
            get {
                object obj = ResourceManager.GetObject("_05_07_沙罗曼蛇", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _05_08_绿色兵团 {
            get {
                object obj = ResourceManager.GetObject("_05_08_绿色兵团", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _05_09_飞狼 {
            get {
                object obj = ResourceManager.GetObject("_05_09_飞狼", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _05_10_直升机 {
            get {
                object obj = ResourceManager.GetObject("_05_10_直升机", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _06_01_射击靶场 {
            get {
                object obj = ResourceManager.GetObject("_06_01_射击靶场", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _06_02_雪人 {
            get {
                object obj = ResourceManager.GetObject("_06_02_雪人", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _06_03_冰球联赛 {
            get {
                object obj = ResourceManager.GetObject("_06_03_冰球联赛", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _06_04_赤色要塞 {
            get {
                object obj = ResourceManager.GetObject("_06_04_赤色要塞", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _06_05_将棋 {
            get {
                object obj = ResourceManager.GetObject("_06_05_将棋", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _06_06_影子传说 {
            get {
                object obj = ResourceManager.GetObject("_06_06_影子传说", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _06_07_南北拳 {
            get {
                object obj = ResourceManager.GetObject("_06_07_南北拳", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _06_08_忍者 {
            get {
                object obj = ResourceManager.GetObject("_06_08_忍者", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _06_09_功夫小子 {
            get {
                object obj = ResourceManager.GetObject("_06_09_功夫小子", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _06_10_美人鱼 {
            get {
                object obj = ResourceManager.GetObject("_06_10_美人鱼", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _07_01_淘金者 {
            get {
                object obj = ResourceManager.GetObject("_07_01_淘金者", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _07_02_淘金者2 {
            get {
                object obj = ResourceManager.GetObject("_07_02_淘金者2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _07_03_溜溜球 {
            get {
                object obj = ResourceManager.GetObject("_07_03_溜溜球", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _07_04_桌球 {
            get {
                object obj = ResourceManager.GetObject("_07_04_桌球", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _07_05_金刚组合 {
            get {
                object obj = ResourceManager.GetObject("_07_05_金刚组合", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _07_06_4人麻将 {
            get {
                object obj = ResourceManager.GetObject("_07_06_4人麻将", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _07_07_台湾麻将 {
            get {
                object obj = ResourceManager.GetObject("_07_07_台湾麻将", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _07_08_猫捉老鼠 {
            get {
                object obj = ResourceManager.GetObject("_07_08_猫捉老鼠", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _07_09_水管玛莉 {
            get {
                object obj = ResourceManager.GetObject("_07_09_水管玛莉", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _07_10_迷你昆虫 {
            get {
                object obj = ResourceManager.GetObject("_07_10_迷你昆虫", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _08_01_战斗营 {
            get {
                object obj = ResourceManager.GetObject("_08_01_战斗营", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _08_02_忍者2 {
            get {
                object obj = ResourceManager.GetObject("_08_02_忍者2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _08_03_爱的小屋 {
            get {
                object obj = ResourceManager.GetObject("_08_03_爱的小屋", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _08_04_黑白棋 {
            get {
                object obj = ResourceManager.GetObject("_08_04_黑白棋", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _08_05_小精灵 {
            get {
                object obj = ResourceManager.GetObject("_08_05_小精灵", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _08_06_第八连 {
            get {
                object obj = ResourceManager.GetObject("_08_06_第八连", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _08_07_南极冒险 {
            get {
                object obj = ResourceManager.GetObject("_08_07_南极冒险", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _08_08_扑克集锦 {
            get {
                object obj = ResourceManager.GetObject("_08_08_扑克集锦", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _08_09_动物小镇 {
            get {
                object obj = ResourceManager.GetObject("_08_09_动物小镇", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _08_10_大力水手 {
            get {
                object obj = ResourceManager.GetObject("_08_10_大力水手", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _09_01_火箭车 {
            get {
                object obj = ResourceManager.GetObject("_09_01_火箭车", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _09_02_洛克人 {
            get {
                object obj = ResourceManager.GetObject("_09_02_洛克人", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _09_03_四度空间 {
            get {
                object obj = ResourceManager.GetObject("_09_03_四度空间", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _09_04_太空毁灭者 {
            get {
                object obj = ResourceManager.GetObject("_09_04_太空毁灭者", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _09_05_忍者赤影 {
            get {
                object obj = ResourceManager.GetObject("_09_05_忍者赤影", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _09_06_世界桌球赛 {
            get {
                object obj = ResourceManager.GetObject("_09_06_世界桌球赛", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _09_07_红巾特工队 {
            get {
                object obj = ResourceManager.GetObject("_09_07_红巾特工队", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _09_08_潜水艇 {
            get {
                object obj = ResourceManager.GetObject("_09_08_潜水艇", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _09_09_枪战 {
            get {
                object obj = ResourceManager.GetObject("_09_09_枪战", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _09_10_小蜜蜂2 {
            get {
                object obj = ResourceManager.GetObject("_09_10_小蜜蜂2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _10_01_探勘洞穴者 {
            get {
                object obj = ResourceManager.GetObject("_10_01_探勘洞穴者", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _10_02_雷鸟号 {
            get {
                object obj = ResourceManager.GetObject("_10_02_雷鸟号", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _10_03_星际卫士 {
            get {
                object obj = ResourceManager.GetObject("_10_03_星际卫士", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _10_04_星际战士 {
            get {
                object obj = ResourceManager.GetObject("_10_04_星际战士", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _10_05_曲棍球2 {
            get {
                object obj = ResourceManager.GetObject("_10_05_曲棍球2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _10_06_网球 {
            get {
                object obj = ResourceManager.GetObject("_10_06_网球", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _10_07_飞机射击 {
            get {
                object obj = ResourceManager.GetObject("_10_07_飞机射击", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _10_08_玛莉砖块 {
            get {
                object obj = ResourceManager.GetObject("_10_08_玛莉砖块", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _10_09_摔角 {
            get {
                object obj = ResourceManager.GetObject("_10_09_摔角", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _10_10_铁板阵 {
            get {
                object obj = ResourceManager.GetObject("_10_10_铁板阵", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _11_01_羽毛球 {
            get {
                object obj = ResourceManager.GetObject("_11_01_羽毛球", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _11_02_王者之剑 {
            get {
                object obj = ResourceManager.GetObject("_11_02_王者之剑", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _11_03_庸兵 {
            get {
                object obj = ResourceManager.GetObject("_11_03_庸兵", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _11_04_智慧方块1 {
            get {
                object obj = ResourceManager.GetObject("_11_04_智慧方块1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _11_05_火凤凰2 {
            get {
                object obj = ResourceManager.GetObject("_11_05_火凤凰2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _11_06_溜溜球2 {
            get {
                object obj = ResourceManager.GetObject("_11_06_溜溜球2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _11_07_机车大战 {
            get {
                object obj = ResourceManager.GetObject("_11_07_机车大战", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _11_08_巧巧弹 {
            get {
                object obj = ResourceManager.GetObject("_11_08_巧巧弹", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _11_09_飞鸟骑士 {
            get {
                object obj = ResourceManager.GetObject("_11_09_飞鸟骑士", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _11_10_超时空要塞 {
            get {
                object obj = ResourceManager.GetObject("_11_10_超时空要塞", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _12_01_二人麻将 {
            get {
                object obj = ResourceManager.GetObject("_12_01_二人麻将", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _12_02_围棋指南 {
            get {
                object obj = ResourceManager.GetObject("_12_02_围棋指南", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _12_03_摔跤 {
            get {
                object obj = ResourceManager.GetObject("_12_03_摔跤", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _12_04_中国象棋 {
            get {
                object obj = ResourceManager.GetObject("_12_04_中国象棋", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _12_05_暗棋 {
            get {
                object obj = ResourceManager.GetObject("_12_05_暗棋", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _12_06_棒球 {
            get {
                object obj = ResourceManager.GetObject("_12_06_棒球", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _12_07_扑克方块 {
            get {
                object obj = ResourceManager.GetObject("_12_07_扑克方块", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _12_08_太空战舰 {
            get {
                object obj = ResourceManager.GetObject("_12_08_太空战舰", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _12_09_青蛙冒险 {
            get {
                object obj = ResourceManager.GetObject("_12_09_青蛙冒险", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _12_10_圣骑士 {
            get {
                object obj = ResourceManager.GetObject("_12_10_圣骑士", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _13_01_智慧桥 {
            get {
                object obj = ResourceManager.GetObject("_13_01_智慧桥", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _13_02_环游世界80天 {
            get {
                object obj = ResourceManager.GetObject("_13_02_环游世界80天", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _13_03_智慧方块2 {
            get {
                object obj = ResourceManager.GetObject("_13_03_智慧方块2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _13_04_射击方块 {
            get {
                object obj = ResourceManager.GetObject("_13_04_射击方块", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _13_05_新人类 {
            get {
                object obj = ResourceManager.GetObject("_13_05_新人类", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _13_06_相扑 {
            get {
                object obj = ResourceManager.GetObject("_13_06_相扑", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _13_07_铁道王 {
            get {
                object obj = ResourceManager.GetObject("_13_07_铁道王", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _13_08_侦探员 {
            get {
                object obj = ResourceManager.GetObject("_13_08_侦探员", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _13_09_米老鼠 {
            get {
                object obj = ResourceManager.GetObject("_13_09_米老鼠", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _13_10_机动四驱车 {
            get {
                object obj = ResourceManager.GetObject("_13_10_机动四驱车", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _14_01_装甲英雄 {
            get {
                object obj = ResourceManager.GetObject("_14_01_装甲英雄", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _14_02_忍者阿修罗之章 {
            get {
                object obj = ResourceManager.GetObject("_14_02_忍者阿修罗之章", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _14_03_战场之狼 {
            get {
                object obj = ResourceManager.GetObject("_14_03_战场之狼", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _14_04_碰碰赛车手 {
            get {
                object obj = ResourceManager.GetObject("_14_04_碰碰赛车手", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _14_05_冠军保龄球 {
            get {
                object obj = ResourceManager.GetObject("_14_05_冠军保龄球", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _14_06_失落的世界 {
            get {
                object obj = ResourceManager.GetObject("_14_06_失落的世界", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _14_07_空手道精武们 {
            get {
                object obj = ResourceManager.GetObject("_14_07_空手道精武们", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _14_08_快乐水果狸 {
            get {
                object obj = ResourceManager.GetObject("_14_08_快乐水果狸", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _14_09_迷宫组曲 {
            get {
                object obj = ResourceManager.GetObject("_14_09_迷宫组曲", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _14_10_金齿轮战士 {
            get {
                object obj = ResourceManager.GetObject("_14_10_金齿轮战士", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _15_01_太空传说 {
            get {
                object obj = ResourceManager.GetObject("_15_01_太空传说", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _15_02_网球大满贯赛 {
            get {
                object obj = ResourceManager.GetObject("_15_02_网球大满贯赛", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _15_03_虎形直升机 {
            get {
                object obj = ResourceManager.GetObject("_15_03_虎形直升机", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _15_04_金字塔方块 {
            get {
                object obj = ResourceManager.GetObject("_15_04_金字塔方块", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _15_05_油漆精灵 {
            get {
                object obj = ResourceManager.GetObject("_15_05_油漆精灵", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _15_06_金刚数学 {
            get {
                object obj = ResourceManager.GetObject("_15_06_金刚数学", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _15_07_西游记 {
            get {
                object obj = ResourceManager.GetObject("_15_07_西游记", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _15_08_决战X世代 {
            get {
                object obj = ResourceManager.GetObject("_15_08_决战X世代", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _15_09_排球 {
            get {
                object obj = ResourceManager.GetObject("_15_09_排球", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _15_10_地球战士 {
            get {
                object obj = ResourceManager.GetObject("_15_10_地球战士", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
